--Q1.What is the total revenue generated by male vs. female customer?
SELECT gender, SUM(purchase_amount) AS "revenue"
FROM customer
GROUP BY gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)

--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric), 2) AS "Average Product Review Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5

--Q4. Compare the average Purchase Amounts between standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS "Average Purchase Amount"
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) AS "Total Customers",
ROUND(AVG(purchase_amount), 2) AS "Average Spend",
ROUND(SUM(purchase_amount), 2) AS "Total Revenue"
FROM customer
GROUP BY subscription_status
ORDER BY "Average Spend", "Total Revenue" DESC

--Q6. Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) AS "Discount Applied Rate"
FROM customer
GROUP BY item_purchased
ORDER BY "Discount Applied Rate" DESC
LIMIT 5

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returniung'
	ELSE 'Loyal'
	END AS "Customer Segment"
FROM customer)
SELECT "Customer Segment", COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY "Customer Segment"


--Q8. What are the top 3 most purchased products within each category?
WITH item_count AS(
SELECT category, item_purchased,
COUNT(customer_id) AS "Total Orders",
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS "Item Rank"
FROM customer
GROUP BY category, item_purchased)

SELECT "Item Rank", category, item_purchased, "Total Orders"
FROM item_count
WHERE "Item Rank" <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS "Repeat Buyers"
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10. What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) AS "Total Revenue"
FROM customer
GROUP BY age_group
ORDER BY "Total Revenue" DESC